name: Build and publish Docker images
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get tag version number
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Minifying Chatbot scripts
      uses: nizarmah/auto-minify@v2.1
      with:
        directory: './backend/files/system/openai/front.files/chat'
        output: './backend/files/system/openai/front.files/chat'
    - name: Minifying CAPTCHA script
      uses: nizarmah/auto-minify@v2.1
      with:
        directory: './backend/files/system/misc'
        output: './backend/files/system/misc'
    - name: Build and push Docker images for backend and frontend
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

        docker build -t servergardens/magic-backend:latest -f ./docker.backend .
        docker build -t servergardens/magic-backend:${{ steps.get_version.outputs.VERSION }} -f ./docker.backend .
        docker push servergardens/magic-backend:latest
        docker push servergardens/magic-backend:${{ steps.get_version.outputs.VERSION }}

        docker build -t servergardens/magic-frontend:latest -f ./docker.frontend .
        docker build -t servergardens/magic-frontend:${{ steps.get_version.outputs.VERSION }} -f ./docker.frontend .
        docker push servergardens/magic-frontend:latest
        docker push servergardens/magic-frontend:${{ steps.get_version.outputs.VERSION }}

        zip -r magic-${{ steps.get_version.outputs.VERSION }}.zip *
        curl -X PUT -H "Content-Type: multipart/form-data"  -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" -F "folder=/etc/releases/" -F "file=@magic-${{ steps.get_version.outputs.VERSION }}.zip" "https://ainiro.io/magic/system/file-system/file"

        zip -r magic.zip *
        curl -X PUT -H "Content-Type: multipart/form-data"  -H "Authorization: Bearer ${{ secrets.API_TOKEN }}" -F "folder=/etc/releases/" -F "file=@magic.zip" "https://ainiro.io/magic/system/file-system/file"
